#!/usr/bin/env bash

set -Eeuo pipefail

main() {
  check_for_new_commits
  build
}

check_for_new_commits() {
  # Check if we actually have commits to push
  local commits
  commits=$(git log @{u}..)
  if [ -z "$commits" ]; then
      exit 0
  fi
}

build() {
  "${PWD}/build.sh"
}

main "${@}"
