services:
  db:
    image: postgres:14
    # restart: always
    environment:
      POSTGRES_USER: INVOICE_MANAGER
      POSTGRES_PASSWORD: INVOICE_MANAGER
    ports:
      - 5432:5432
  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080